---
  title: "Discovering Focused Microgenre Communities: Microgenre Analysis"
  author: "Omar Lizardo"
  date: "`r Sys.Date()`"
  output:
    html_document: default
---

# Setup
```{r setup}
    knitr::opts_chunk$set(include=FALSE, echo = TRUE, warning = FALSE, message = FALSE)
    library(conflicted)
    library(dendextend)
    library(haven)
    library(here)
    library(sjPlot)
    library(tidyverse)
    load(file= here("dat", "lclust-res.RData"))
```

```{r Importing and creating two mode data frame of people by genres}
    taste.dat <- read_dta("C:/Users/Omar Lizardo/Google Drive/MISC DATA SOURCES/SSI-2012/SSI2012.dta")
    taste.dat <- taste.dat %>% 
      dplyr::select("id", ends_with(c("lis", "like")), -starts_with("none")) %>% 
      dplyr::select(c(1:41)) %>% 
      na.omit() %>% 
      mutate(Classical = classicallike * classicallis,
             Opera = operalike * operalis,
             Jazz = jazzlike * jazzlis,
             Broadway = bwaystlike * bwaystlis,
             Easy = moodezlike * moodezlis, 
             Bigband = bbandlike * bbandlis,
             Classic_Rock = croldlike * croldlis,
             Country = countrylike * countrylis,
             Bluegrass = blueglike * blueglis,
             Folk = folklike * folklis,
             Gospel = hymgoslike * hymgoslis,
             Latin = latlpsallike * latspsallis,
             Rap_Hip_Hop = raphiphoplike * raphiphoplis,
             Blues_RandB = blurblike * blurblis,
             Reggae = reggaelike * reggaelis,
             Pop = toppoplike * toppoplis,
             Contemp_Rock = controcklike * controcklis,
             Indie_Alt = indaltlike * indaltlis,
             Dance_Club = danclublike * danclublis,
             Heavy_Metal = hvymtllike * hvymtllis
             ) %>%  #people are linked to genres that the both like and listen to
      dplyr::select(id, Classical:Heavy_Metal)
```

```{r Performing Link Clustering}
    lclust.res <- hclust(ldist.res$dist, method = "ward.D2") #clustering of link by link distance matrixco
    lclust.dend <- as.dendrogram(lclust.res) #transforming link clustering into dendrogram
```

```{r}
    source(here("Functions", "micro.genre.dat.R"))
    source(here("Functions", "demog.dat.R"))
    source(here("Functions", "genre.reg.mods.R"))
    m <- genre.reg.mods("Country", k = 7,
                        xvars = c("educ", "race", "gender", "age.n",
                           "subjclass"))
    tab_model(m, digits = 3, show.ci = FALSE, 
              file = here("Tabs", "reg-tab-latin.html"))
```


```{r}
    source(here("Functions", "micro.genre.dat.R"))
    source(here("Functions", "demog.dat.R"))
    latin.micro <- micro.genre.dat("Latin", k = 6)$all %>% 
      left_join(demog.dat())
    head(latin.micro)
    mod1 <- lm(as.numeric(Latin_1) ~ educ + race + gender + age.n, 
               data = latin.micro)
    mod2 <- lm(as.numeric(Latin_2) ~ educ + race + gender + age.n, 
               data = latin.micro)
    mod3 <- lm(as.numeric(Latin_3) ~ educ + race + gender + age.n, 
               data = latin.micro)
    mod4 <- lm(as.numeric(Latin_4) ~ educ + race + gender + age.n, 
               data = latin.micro)
    mod5 <- lm(as.numeric(Latin_5) ~ educ + race + gender + age.n, 
               data = latin.micro)
    mod6 <- lm(as.numeric(Latin_6) ~ educ + race + gender + age.n, 
               data = latin.micro)
    tab_model(mod1, mod2, mod3, mod4, mod5, mod6,
                show.ci = FALSE, auto.label = FALSE, digits = 3,
                #dv.labels = c(),
                #rm.terms = c(), 
                #pred.labels = c(), 
                file = here("Tabs", "reg-tab-latin.html") 
              )
    #webshot(here("Tabs", "reg-tab-latin.html"), here("Tabs", "reg-latin-ASR.png"))
```


